package io.acellab.service.web.startline.Config;


import java.util.ArrayList;

//Spring dependency
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;


// Root Configuration
@Configuration
@ComponentScan(basePackages = "io.acellab.service.web.startline.Controller")
public class AppConfig {
	
	//Define Beans here
	private ArrayList<String> countries;
	
	private ArrayList<String> industries;
	
	private ArrayList<String> countrycodes;
	
	private ArrayList<String> fundingrounds;
	
	@Bean
	public ArrayList<String> countriesList(){
		countries = new ArrayList<>();
		
		countries.add("Afghanistan");
		countries.add("Albania");
		countries.add("Algeria");
		countries.add("Andorra");
		countries.add("Angola");
		countries.add("Antigua and Barbuda");
		countries.add("Argentina");
		countries.add("Armenia");
		countries.add("Australia");
		countries.add("Austria");
		countries.add("Azerbaijan");
		countries.add("Bahamas");
		countries.add("Bahrain");
		countries.add("Bangladesh");
		countries.add("Barbados");
		countries.add("Belarus");
		countries.add("Belgium");
		countries.add("Belize");
		countries.add("Benin");
		countries.add("Bhutan");
		countries.add("Bolivia");
		countries.add("Bosnia and Herzegovina");
		countries.add("Botswana");
		countries.add("Brazil");
		countries.add("Brunei");
		countries.add("Bulgaria");
		countries.add("Burkina Faso");
		countries.add("Burundi");
		countries.add("Côte d'Ivoire");
		countries.add("Cabo Verde");
		countries.add("Cambodia");
		countries.add("Cameroon");
		countries.add("Canada");
		countries.add("Central African Republic");
		countries.add("Chad");
		countries.add("Chile");
		countries.add("China");
		countries.add("Colombia");
		countries.add("Comoros");
		countries.add("Congo (Congo-Brazzaville)");
		countries.add("Costa Rica");
		countries.add("Croatia");
		countries.add("Cuba");
		countries.add("Cyprus");
		countries.add("Czechia");
		countries.add("Democratic Republic of the Congo");
		countries.add("Denmark");
		countries.add("Djibouti");
		countries.add("Dominica");
		countries.add("Dominican Republic");
		countries.add("Ecuador");
		countries.add("Egypt");
		countries.add("El Salvador");
		countries.add("Equatorial Guinea");
		countries.add("Eritrea");
		countries.add("Estonia");
		countries.add("Eswatini");
		countries.add("Ethiopia");
		countries.add("Fiji");
		countries.add("Finland");
		countries.add("France");
		countries.add("Gabon");
		countries.add("Gambia");
		countries.add("Georgia");
		countries.add("Germany");
		countries.add("Ghana");
		countries.add("Greece");
		countries.add("Grenada");
		countries.add("Guatemala");
		countries.add("Guinea");
		countries.add("Guinea-Bissau");
		countries.add("Guyana");
		countries.add("Haiti");
		countries.add("Holy See");
		countries.add("Honduras");
		countries.add("Hong Kong");
		countries.add("Hungary");
		countries.add("Iceland");
		countries.add("India");
		countries.add("Indonesia");
		countries.add("Iran");
		countries.add("Iraq");
		countries.add("Ireland");
		countries.add("Israel");
		countries.add("Italy");
		countries.add("Jamaica");
		countries.add("Japan");
		countries.add("Jordan");
		countries.add("Kazakhstan");
		countries.add("Kenya");
		countries.add("Kiribati");
		countries.add("Kuwait");
		countries.add("Kyrgyzstan");
		countries.add("Laos");
		countries.add("Latvia");
		countries.add("Lebanon");
		countries.add("Lesotho");
		countries.add("Liberia");
		countries.add("Libya");
		countries.add("Liechtenstein");
		countries.add("Lithuania");
		countries.add("Luxembourg");
		countries.add("Madagascar");
		countries.add("Malawi");
		countries.add("Malaysia");
		countries.add("Maldives");
		countries.add("Mali");
		countries.add("Malta");
		countries.add("Marshall Islands");
		countries.add("Mauritania");
		countries.add("Mauritius");
		countries.add("Mexico");
		countries.add("Micronesia");
		countries.add("Moldova");
		countries.add("Monaco");
		countries.add("Mongolia");
		countries.add("Montenegro");
		countries.add("Morocco");
		countries.add("Mozambique");
		countries.add("Myanmar");
		countries.add("Namibia");
		countries.add("Nauru");
		countries.add("Nepal");
		countries.add("Netherlands");
		countries.add("New Zealand");
		countries.add("Nicaragua");
		countries.add("Niger");
		countries.add("Nigeria");
		countries.add("North Korea");
		countries.add("North Macedonia");
		countries.add("Norway");
		countries.add("Oman");
		countries.add("Pakistan");
		countries.add("Palau");
		countries.add("Palestine State");
		countries.add("Panama");
		countries.add("Papua New Guinea");
		countries.add("Paraguay");
		countries.add("Peru");
		countries.add("Philippines");
		countries.add("Poland");
		countries.add("Portugal");
		countries.add("Qatar");
		countries.add("Romania");
		countries.add("Russia");
		countries.add("Rwanda");
		countries.add("Saint Kitts and Nevis");
		countries.add("Saint Lucia");
		countries.add("Saint Vincent and the Grenadines");
		countries.add("Samoa");
		countries.add("San Marino");
		countries.add("Sao Tome and Principe");
		countries.add("Saudi Arabia");
		countries.add("Senegal");
		countries.add("Serbia");
		countries.add("Seychelles");
		countries.add("Sierra Leone");
		countries.add("Singapore");
		countries.add("Slovakia");
		countries.add("Slovenia");
		countries.add("Solomon Islands");
		countries.add("Somalia");
		countries.add("South Africa");
		countries.add("South Korea");
		countries.add("South Sudan");
		countries.add("Spain");
		countries.add("Sri Lanka");
		countries.add("Sudan");
		countries.add("Suriname");
		countries.add("Sweden");
		countries.add("Switzerland");
		countries.add("Syria");
		countries.add("Taiwan");
		countries.add("Tajikistan");
		countries.add("Tanzania");
		countries.add("Thailand");
		countries.add("Timor-Leste");
		countries.add("Togo");
		countries.add("Tonga");
		countries.add("Trinidad and Tobago");
		countries.add("Tunisia");
		countries.add("Turkey");
		countries.add("Turkmenistan");
		countries.add("Tuvalu");
		countries.add("Uganda");
		countries.add("Ukraine");
		countries.add("United Arab Emirates");
		countries.add("United Kingdom");
		countries.add("United States of America");
		countries.add("Uruguay");
		countries.add("Uzbekistan");
		countries.add("Vanuatu");
		countries.add("Venezuela");
		countries.add("Vietnam");
		countries.add("Yemen");
		countries.add("Zambia");
		countries.add("Zimbabwe");
		
		return this.countries;
	}

	@Bean
	public ArrayList<String> industriesList(){
		industries = new ArrayList<>();
		
		industries.add("Agriculture - Dairy");
		industries.add("Agriculture - Farming");
		industries.add("Agriculture - Fishery");
		industries.add("Agriculture - Ranching");
		industries.add("Arts - Arts & Crafts");
		industries.add("Arts - Fine Art");
		industries.add("Arts - Performing Arts");
		industries.add("Arts - Photography");
		industries.add("Carbon Management - Carbon Capture");
		industries.add("Carbon Management - Carbon Trading");
		industries.add("Carbon Management - Embodied Carbon Calculations");
		industries.add("Carbon Management - Emission Management");
		industries.add("Carbon Management - LCA Consultation");
		industries.add("Construction - BIM");
		industries.add("Construction - Building Materials");
		industries.add("Construction - Civil Engineering");
		industries.add("Construction - Construction Robots");
		industries.add("Construction - Contractor / sub-contractor");
		industries.add("Construction - Digital Twins");
		industries.add("Construction - Green Materials");
		industries.add("Construction - Modular Construction");
		industries.add("Construction - Smart Office");
		industries.add("Construction - Surveyor");
		industries.add("Construction - Waste Management");
		industries.add("Consumer Goods - Apparel & Fashion");
		industries.add("Consumer Goods - Consumer Electronics");
		industries.add("Consumer Goods - Consumer Services");
		industries.add("Consumer Goods - Cosmetics");
		industries.add("Consumer Goods - FMCG");
		industries.add("Consumer Goods - Food & Beverages");
		industries.add("Consumer Goods - Furniture");
		industries.add("Consumer Goods - Luxury Goods & Jewellery");
		industries.add("Consumer Goods - Sporting Goods");
		industries.add("Consumer Goods - Tobacco");
		industries.add("Corporate Services - Accounting Services");
		industries.add("Corporate Services - Business Supplies & Equipment");
		industries.add("Corporate Services - Environmental Services");
		industries.add("Corporate Services - Events Services");
		industries.add("Corporate Services - Executive Office");
		industries.add("Corporate Services - Facilities Services");
		industries.add("Corporate Services - Human Resources");
		industries.add("Corporate Services - Information Services");
		industries.add("Corporate Services - Management Consulting");
		industries.add("Corporate Services - Outsourcing/Offshoring");
		industries.add("Corporate Services - Professional Training & Coaching");
		industries.add("Corporate Services - Security & Investigations");
		industries.add("Corporate Services - Staffing & Recruiting");
		industries.add("Design - Architecture & Planning");
		industries.add("Design - Design");
		industries.add("Design - Graphic Design");
		industries.add("eCommerce - Online Shop");
		industries.add("eCommerce - Payment Gateway");
		industries.add("Education - Education Management");
		industries.add("Education - E-Learning");
		industries.add("Education - Higher Education");
		industries.add("Education - Primary / Secondary Education");
		industries.add("Education - Research");
		industries.add("Energy and Mining - Mining & Metals");
		industries.add("Energy and Mining - Oil & Energy");
		industries.add("Energy and Mining - Utilities");
		industries.add("Entertainment - Animation");
		industries.add("Entertainment - Broadcast Media");
		industries.add("Entertainment - Computer Games");
		industries.add("Entertainment - Entertainment");
		industries.add("Entertainment - Media Production");
		industries.add("Entertainment - Mobile Games");
		industries.add("Entertainment - Motion Pictures & Film");
		industries.add("Entertainment - Music");
		industries.add("Finance - Banking");
		industries.add("Finance - Capital Markets");
		industries.add("Finance - Family Office");
		industries.add("Finance - Financial Services");
		industries.add("Finance - Insurance Brokage");
		industries.add("Finance - Investment Banking");
		industries.add("Finance - Investment Management");
		industries.add("Finance - Re-Insurance Service");
		industries.add("Finance - Venture Capital & Private Equity");
		industries.add("Hardware and Networking - Computer Hardware");
		industries.add("Hardware and Networking - Computer Networking");
		industries.add("Hardware and Networking - Nanotechnology");
		industries.add("Hardware and Networking - Semiconductors");
		industries.add("Hardware and Networking - Telecommunications");
		industries.add("Hardware and Networking - Wireless Product & Technology");
		industries.add("Healthcare - Biotechnology");
		industries.add("Healthcare - Hospital & Health Care");
		industries.add("Healthcare - Medical Device");
		industries.add("Healthcare - Medical Practice");
		industries.add("Healthcare - Mental Health Care");
		industries.add("Healthcare - Pharmaceuticals");
		industries.add("Healthcare - Veterinary");
		industries.add("Legal - Alternative Dispute Resolution");
		industries.add("Legal - Law Practice");
		industries.add("Legal - Legal Services");
		industries.add("Manufacturing - Automotive");
		industries.add("Manufacturing - Aviation & Aerospace");
		industries.add("Manufacturing - Chemicals");
		industries.add("Manufacturing - Defense & Space");
		industries.add("Manufacturing - Electrical & Electronic Manufacturing");
		industries.add("Manufacturing - Food Production");
		industries.add("Manufacturing - Glass, Ceramics & Concrete");
		industries.add("Manufacturing - Industrial Automation");
		industries.add("Manufacturing - Machinery");
		industries.add("Manufacturing - Mechanical or Industrial Engineering");
		industries.add("Manufacturing - Packaging & Containers");
		industries.add("Manufacturing - Paper & Forest Products");
		industries.add("Manufacturing - Plastics");
		industries.add("Manufacturing - Railroad Manufacture");
		industries.add("Manufacturing - Renewables & Environment");
		industries.add("Manufacturing - Shipbuilding");
		industries.add("Media and Communications - Market Research");
		industries.add("Media and Communications - Marketing & Advertising");
		industries.add("Media and Communications - Newspapers");
		industries.add("Media and Communications - Online Media");
		industries.add("Media and Communications - Printing");
		industries.add("Media and Communications - Public Relations & Communications");
		industries.add("Media and Communications - Publishing");
		industries.add("Media and Communications - Translation & Localization");
		industries.add("Media and Communications - Writing & Editing");
		industries.add("Nonprofit - Civic & Social Organization");
		industries.add("Nonprofit - Fundraising");
		industries.add("Nonprofit - Individual & Family Services");
		industries.add("Nonprofit - International Trade & Development");
		industries.add("Nonprofit - Libraries");
		industries.add("Nonprofit - Museums & Institutions");
		industries.add("Nonprofit - Non-Profit Organization Management");
		industries.add("Nonprofit - Philanthropy");
		industries.add("Nonprofit - Program Development");
		industries.add("Nonprofit - Religious Institutions");
		industries.add("Nonprofit - Think Tanks");
		industries.add("Public administration - Government Administration");
		industries.add("Public administration - Government Relations");
		industries.add("Public administration - International Affairs");
		industries.add("Public administration - Judiciary");
		industries.add("Public administration - Legislative Office");
		industries.add("Public administration - Political Organization");
		industries.add("Public administration - Public Policy");
		industries.add("Public Safety - Law Enforcement");
		industries.add("Public Safety - Military");
		industries.add("Public Safety - Public Safety");
		industries.add("Real Estate - Commercial Real Estate");
		industries.add("Real Estate - Property Management Services");
		industries.add("Real Estate - Real Estate Broker / Agent");
		industries.add("Real Estate - Residential Real Estate");
		industries.add("Recreation and Travel - Airlines/Aviation");
		industries.add("Recreation and Travel - Gambling & Casinos");
		industries.add("Recreation and Travel - Hospitality");
		industries.add("Recreation and Travel - Leisure, Travel & Tourism");
		industries.add("Recreation and Travel - Recreational Facilities & Services");
		industries.add("Recreation and Travel - Restaurants");
		industries.add("Recreation and Travel - Sports");
		industries.add("Recycle Business - Recycle Park");
		industries.add("Recycle Business - Upcycling Product");
		industries.add("Recycle Business - Waste Collection");
		industries.add("Retail - Retailer");
		industries.add("Retail - Supermarkets");
		industries.add("Retail - Wholesaler");
		industries.add("Smart City - City Information Modelling");
		industries.add("Smart City - Emergency Management");
		industries.add("Smart City - Geographic Information System");
		industries.add("Smart City - Smart Industry Park");
		industries.add("Smart City - Smart Parking");
		industries.add("Smart City - Smart Security");
		industries.add("Software and IT Services - Computer & Network Security");
		industries.add("Software and IT Services - Computer Software");
		industries.add("Software and IT Services - Information Technology & Services");
		industries.add("Software and IT Services - Internet");
		industries.add("Textiles - Design");
		industries.add("Textiles - Knitting");
		industries.add("Textiles - Materials Development");
		industries.add("Transportation and Logistics - Import & Export");
		industries.add("Transportation and Logistics - Logistics & Supply Chain");
		industries.add("Transportation and Logistics - Maritime");
		industries.add("Transportation and Logistics - Package/Freight Delivery");
		industries.add("Transportation and Logistics - Transportation/Trucking/Railroad");
		industries.add("Transportation and Logistics - Warehousing");
		industries.add("Wellness and Fitness - Alternative Medicine");
		industries.add("Wellness and Fitness - Personal Coach / Trainer");
		industries.add("Wine and Spirits - Brewery");
		industries.add("Wine and Spirits - Importer / Exporter");
		industries.add("Wine and Spirits - Vine Yard");
		
		return this.industries;
	}
	
	@Bean
	public ArrayList<String> countryCodesList(){
		countrycodes = new ArrayList<>();
		
		countrycodes.add("+1");
		countrycodes.add("+7");
		countrycodes.add("+20");
		countrycodes.add("+27");
		countrycodes.add("+30");
		countrycodes.add("+31");
		countrycodes.add("+32");
		countrycodes.add("+33");
		countrycodes.add("+34");
		countrycodes.add("+36");
		countrycodes.add("+39");
		countrycodes.add("+40");
		countrycodes.add("+41");
		countrycodes.add("+43");
		countrycodes.add("+44");
		countrycodes.add("+45");
		countrycodes.add("+46");
		countrycodes.add("+47");
		countrycodes.add("+48");
		countrycodes.add("+49");
		countrycodes.add("+51");
		countrycodes.add("+52");
		countrycodes.add("+53");
		countrycodes.add("+54");
		countrycodes.add("+55");
		countrycodes.add("+56");
		countrycodes.add("+57");
		countrycodes.add("+58");
		countrycodes.add("+60");
		countrycodes.add("+61");
		countrycodes.add("+62");
		countrycodes.add("+63");
		countrycodes.add("+64");
		countrycodes.add("+65");
		countrycodes.add("+66");
		countrycodes.add("+81");
		countrycodes.add("+82");
		countrycodes.add("+84");
		countrycodes.add("+86");
		countrycodes.add("+90");
		countrycodes.add("+91");
		countrycodes.add("+92");
		countrycodes.add("+93");
		countrycodes.add("+94");
		countrycodes.add("+95");
		countrycodes.add("+98");
		countrycodes.add("+211");
		countrycodes.add("+212");
		countrycodes.add("+213");
		countrycodes.add("+216");
		countrycodes.add("+218");
		countrycodes.add("+220");
		countrycodes.add("+221");
		countrycodes.add("+222");
		countrycodes.add("+223");
		countrycodes.add("+224");
		countrycodes.add("+225");
		countrycodes.add("+226");
		countrycodes.add("+227");
		countrycodes.add("+228");
		countrycodes.add("+229");
		countrycodes.add("+230");
		countrycodes.add("+231");
		countrycodes.add("+232");
		countrycodes.add("+233");
		countrycodes.add("+234");
		countrycodes.add("+235");
		countrycodes.add("+236");
		countrycodes.add("+237");
		countrycodes.add("+238");
		countrycodes.add("+239");
		countrycodes.add("+240");
		countrycodes.add("+241");
		countrycodes.add("+242");
		countrycodes.add("+243");
		countrycodes.add("+244");
		countrycodes.add("+245");
		countrycodes.add("+246");
		countrycodes.add("+248");
		countrycodes.add("+249");
		countrycodes.add("+250");
		countrycodes.add("+251");
		countrycodes.add("+252");
		countrycodes.add("+253");
		countrycodes.add("+254");
		countrycodes.add("+255");
		countrycodes.add("+256");
		countrycodes.add("+257");
		countrycodes.add("+258");
		countrycodes.add("+260");
		countrycodes.add("+261");
		countrycodes.add("+262");
		countrycodes.add("+263");
		countrycodes.add("+264");
		countrycodes.add("+265");
		countrycodes.add("+266");
		countrycodes.add("+267");
		countrycodes.add("+268");
		countrycodes.add("+269");
		countrycodes.add("+290");
		countrycodes.add("+291");
		countrycodes.add("+297");
		countrycodes.add("+298");
		countrycodes.add("+299");
		countrycodes.add("+350");
		countrycodes.add("+351");
		countrycodes.add("+352");
		countrycodes.add("+353");
		countrycodes.add("+354");
		countrycodes.add("+355");
		countrycodes.add("+356");
		countrycodes.add("+357");
		countrycodes.add("+358");
		countrycodes.add("+359");
		countrycodes.add("+370");
		countrycodes.add("+371");
		countrycodes.add("+372");
		countrycodes.add("+373");
		countrycodes.add("+374");
		countrycodes.add("+375");
		countrycodes.add("+376");
		countrycodes.add("+377");
		countrycodes.add("+378");
		countrycodes.add("+379");
		countrycodes.add("+380");
		countrycodes.add("+381");
		countrycodes.add("+382");
		countrycodes.add("+383");
		countrycodes.add("+385");
		countrycodes.add("+386");
		countrycodes.add("+387");
		countrycodes.add("+389");
		countrycodes.add("+420");
		countrycodes.add("+421");
		countrycodes.add("+423");
		countrycodes.add("+500");
		countrycodes.add("+501");
		countrycodes.add("+502");
		countrycodes.add("+503");
		countrycodes.add("+504");
		countrycodes.add("+505");
		countrycodes.add("+506");
		countrycodes.add("+507");
		countrycodes.add("+508");
		countrycodes.add("+509");
		countrycodes.add("+590");
		countrycodes.add("+591");
		countrycodes.add("+592");
		countrycodes.add("+593");
		countrycodes.add("+595");
		countrycodes.add("+597");
		countrycodes.add("+598");
		countrycodes.add("+599");
		countrycodes.add("+670");
		countrycodes.add("+672");
		countrycodes.add("+673");
		countrycodes.add("+674");
		countrycodes.add("+675");
		countrycodes.add("+676");
		countrycodes.add("+677");
		countrycodes.add("+678");
		countrycodes.add("+679");
		countrycodes.add("+680");
		countrycodes.add("+681");
		countrycodes.add("+682");
		countrycodes.add("+683");
		countrycodes.add("+685");
		countrycodes.add("+686");
		countrycodes.add("+687");
		countrycodes.add("+688");
		countrycodes.add("+689");
		countrycodes.add("+690");
		countrycodes.add("+691");
		countrycodes.add("+692");
		countrycodes.add("+850");
		countrycodes.add("+852");
		countrycodes.add("+853");
		countrycodes.add("+855");
		countrycodes.add("+856");
		countrycodes.add("+880");
		countrycodes.add("+886");
		countrycodes.add("+960");
		countrycodes.add("+961");
		countrycodes.add("+962");
		countrycodes.add("+963");
		countrycodes.add("+964");
		countrycodes.add("+965");
		countrycodes.add("+966");
		countrycodes.add("+967");
		countrycodes.add("+968");
		countrycodes.add("+970");
		countrycodes.add("+971");
		countrycodes.add("+972");
		countrycodes.add("+973");
		countrycodes.add("+974");
		countrycodes.add("+975");
		countrycodes.add("+976");
		countrycodes.add("+977");
		countrycodes.add("+992");
		countrycodes.add("+993");
		countrycodes.add("+994");
		countrycodes.add("+995");
		countrycodes.add("+996");
		countrycodes.add("+998");
		
		return this.countrycodes;
	}
	
	@Bean
	public ArrayList<String> fundingsRoundList(){
		fundingrounds = new ArrayList<>();
		
		fundingrounds.add("Accelerator Round");
		fundingrounds.add("Pre-Seed Round");
		fundingrounds.add("Seed Round");
		fundingrounds.add("Pre-A Round");
		fundingrounds.add("Series A");
		fundingrounds.add("Series A+");
		fundingrounds.add("Pre-B Round");
		fundingrounds.add("Series B");
		fundingrounds.add("Series B+");
		fundingrounds.add("Series C");
		fundingrounds.add("Series C+");
		fundingrounds.add("Series D");
		fundingrounds.add("Series D+");
		fundingrounds.add("Series E");
		fundingrounds.add("Series F");
		fundingrounds.add("Series G");
		fundingrounds.add("Series H");
		fundingrounds.add("Late Stage Round");
		fundingrounds.add("Mezzanine Financing");
		fundingrounds.add("Bridge Round");
		fundingrounds.add("Strategic Round");
		fundingrounds.add("Follow-on Round");
		fundingrounds.add("Extension Round");
		fundingrounds.add("Parallel Round");
		fundingrounds.add("Acquisition");
		fundingrounds.add("Acqui-hire");
		fundingrounds.add("Buyout");
		fundingrounds.add("Takeover");
		fundingrounds.add("Exit");
		fundingrounds.add("IPO");
		fundingrounds.add("Post IPO Debt");
		fundingrounds.add("Post IPO Equity");
		fundingrounds.add("Merger & Acquisition");
		fundingrounds.add("Not disclosed");
		fundingrounds.add("Convertible Note");
		fundingrounds.add("Corporate Bond");
		fundingrounds.add("Corporate Round");
		fundingrounds.add("Crowdfunding");
		fundingrounds.add("Debt Financing");
		fundingrounds.add("Equity");
		fundingrounds.add("Equity Crowdfunding");
		fundingrounds.add("Grant");
		fundingrounds.add("Initial Coin Offering (ICO)");
		fundingrounds.add("Non-equity Assistance");
		fundingrounds.add("Private Equity");
		fundingrounds.add("Product Crowdfunding");
		fundingrounds.add("Registered Capital");
		fundingrounds.add("Secondary Market");
		fundingrounds.add("Strategic Investment");
		fundingrounds.add("Venture - Series Unknown");
		fundingrounds.add("ICO Pre-sale");
		fundingrounds.add("Regulation Crowdfunding (Reg CF)");
		fundingrounds.add("Simple Agreement for Future Equity (SAFE)");
		fundingrounds.add("Angel Round");
		
		return this.fundingrounds;
	}
	
}
